### PR TITLE
Added iDrac Splunk plugin

### PR DESCRIPTION
**Pull request by srinivasadatari**
Initial commit.

### CODE REVIEW

**Comment by grantcurell** [comment]
Glanced through the code. Apologies if I'm missing something silly. How does this code differ from: https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/main/cmd/splunkpump/splunkpump.go

**Comment by srinivasadatari** [comment]
> Glanced through the code. Apologies if I'm missing something silly. How does this code differ from: https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/main/cmd/splunkpump/splunkpump.go

I am not too familiar with splunkpump, but my understanding is that code is just the translator and what this PR has is a plugin that reads the metrics and then does the splunk app translation. This is from an iDrac splunk plugin gig work.

**Comment by cjmadathil** [comment]
This new project is an IDRAC SDK application (which is a stripped down version of reference toolset pipeline). Essentially this application eventually when it is completed, will run on iDRAC as a container (making use of underlying iDRAC SDK infrastructure) which connects directly to local HTTP endpoint to received SSE stream and send the metrics directly to configured SPLUNK server URL.

**Comment by cjmadathil** [comment]
@srinivasadatari , I propose following directory structure. cmd/idracsdkapps/splunkapp.

This is a good start. We should extract common abstractions (for example for sse stream consumer which can be used by similar sdk apps ) from this file as an interface definition.

**Review by cjmadathil — APPROVED** [review]

**Comment by grantcurell** [comment]
> > Glanced through the code. Apologies if I'm missing something silly. How does this code differ from: https://github.com/dell/iDRAC-Telemetry-Reference-Tools/blob/main/cmd/splunkpump/splunkpump.go
> 
> I am not too familiar with splunkpump, but my understanding is that code is just the translator and what this PR has is a plugin that reads the metrics and then does the splunk app translation. This is from an iDrac splunk plugin gig work.

That's what Splunkpump does - it reads the metrics from Apache and then puts them in Splunk. Suggest we deconflict which code we are going to use as these two things appear to have identical functionality.

**Comment by grantcurell** [comment]
Redfishread reads the SSE stream, places it in Apache MQ, and then Splunkpump (or other pump) reads it and puts it into the target application.

I don't think it makes sense necessarily to bypass the existing architecture (IE: ApacheMQ and Redfishread).

Feel free to let me know if I've misunderstood though

**Comment by srinivasadatari** [comment]
> 

See Cyril's response above. We are not depending on the MQ infra. We are directly talking to the SSE endpoint and extracting the enabled metrics, translating them, and sending them to a splunk app URL. As I mentioned before, this is a splunk SDK plugin and part of a gig. Maybe a quick chat with Cyril may clear the ask ?

**Comment by srinivasadatari** [comment]
> @srinivasadatari , I propose following directory structure. cmd/idracsdkapps/splunkapp.
> 
> This is a good start. We should extract common abstractions (for example for sse stream consumer which can be used by similar sdk apps ) from this file as an interface definition.

Sure, we can move the code to any location. Heidi and I picked this as a starting point.

**Comment by grantcurell** [comment]
*shrugs* I'm a tagalong from outside PG so not really my call 😂

That said, from a software engineering perspective what I'm getting at is that we should probably find a way to use the existing code as a library rather than duplicate it. Ex: Your code could call functions from redfishread / splunkpump or vice versa.

Otherwise we have two sets of code doing exactly the same things that will have to be maintained separately.

**Comment by windsparks33** [comment]
Hi Grant! 

I also had the same question too and followed up with Michael.

The GIG work is designed to provide another mechanism to gain the Telemetry data while reducing moving parts (activemq) and user setup.   The thought is instead of creating an SSE session and feeding the data to active mq,  we can create an SSE session and send it direct to interesting parties (splunk and more).


This is a great start and works.  I agree with Cyril that we can create an internal go package for the SSE stream.

**Comment by windsparks33** [comment]
We could explore having it integrated as part of redfish read...  maybe a separate package that gets called into redfishread?  hmm

**Comment by cjmadathil** [comment]
Some more context on this:
Our first reference toolset - Externally hosted application functions as a many to one telemetry aggregator or a console. This aggregator or the console consumes SSE telemetry stream from the configured iDRAC endpoints and stores data in the respective big database backends for down stream analytics.

IDRAC SDK plugin reference - Make use of iDRAC SDK infrastructure. Bare minimum telemetry to metrics translator, and runs as an iDRAC container based application. Should have minimal overhead and dependencies. We plan to publish Splunk and elastic search reference plugins.

Our goal is to provide various reference architectures for our customers to make use of PowerEdge telemetry. As Grant mentioned we should make use of shared/common code as much as possible.

**Review by windsparks33 — APPROVED** [review]

**Pull request merged**
